name: Main CI

env:
  DOCKER_USER: rossmaclean
  PROJECT_NAME: mongo-cloudron
  CLOUDRON_SERVER: my.rossmac.co.uk
  APP_DOMAIN: mongo.rossmac.co.uk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username ${{ env.DOCKER_USER }} --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:${GITHUB_SHA::7} -t ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:latest .
      - run: docker push ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:${GITHUB_SHA::7}